import Navbar from '@/components/main-nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Leftbar from '@/components/left-bar'
import Rightbar from '@/components/right-bar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-4 bg-background w-screen text-text">
        <Navbar />
        <div className="flex px-8">
          <Leftbar />
          {children}
          <Rightbar />
        </div>
      </div>
      </body>
    </html>
  )
}
